{
    "type": "push",
    "targets": ["stream"],
    "push": {
        "type": "mirror",
        "source_device_iden": "ujBuM9LadhssjB6hGMTY3U",
        "source_user_iden": "ujBuM9Ladhs",
        "client_version": 407,
        "dismissible": True,
        "icon": "/9j/4AAQSkZJRgABAQAAAQABAAD/4gIoSUNDX1BST0ZJTEUAAQEAAAIYAAAAAAQwAABtbnRyUkdCIFhZWiAAAAAAAAAAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAAHRyWFlaAAABZAAAABRnWFlaAAABeAAAABRiWFlaAAABjAAAABRyVFJDAAABoAAAAChnVFJDAAABoAAAAChiVFJDAAABoAAAACh3dHB0AAAByAAAABRjcHJ0AAAB3AAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAFgAAAAcAHMAUgBHAEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFhZWiAAAAAAAABvogAAOPUAAAOQWFlaIAAAAAAAAGKZAAC3hQAAGNpYWVogAAAAAAAAJKAAAA+EAAC2z3BhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABYWVogAAAAAAAA9tYAAQAAAADTLW1sdWMAAAAAAAAAAQAAAAxlblVTAAAAIAAAABwARwBvAG8AZwBsAGUAIABJAG4AYwAuACAAMgAwADEANv/bAEMABgQFBgUEBgYFBgcHBggKEAoKCQkKFA4PDBAXFBgYFxQWFhodJR8aGyMcFhYgLCAjJicpKikZHy0wLSgwJSgpKP/bAEMBBwcHCggKEwoKEygaFhooKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKP/AABEIAFAAUAMBIgACEQEDEQH/xAAcAAACAgMBAQAAAAAAAAAAAAAEBgIFAAMHAQj/xAA0EAABAwMCBQEGBQQDAAAAAAABAgMEAAUREiEGEzFBUWEHIiMycaEIFBYzgUJDUnKRweH/xAAaAQACAwEBAAAAAAAAAAAAAAADBAIFBgAB/8QAJREAAQMDBAMAAwEAAAAAAAAAAQACAwQRIQUSEzFBUWEUMnGB/9oADAMBAAIRAxEAPwBTrKyl693NSiqPGOE9FLHf0FRp6d079rViWMLzYIu43uPEJQ38V0dgdh9TS9LvM6QSOby0eG9vv1oYt14W60EOnwxjq5+qyjhjZ4uVpccdc/ccWr/ZRNeNuut/tuLR/qSK3cs1Atmj8DThMXHSMi3qdGwOdzE+HN/v1phtt+jyyEO/BdPYnY/Q0olHpUSjFKzafHJ8KDJBHJ4sV0ispYsF3UhSY0tWUHZCz29D6Uz1RVFO+B21yrJIzGbFA3Z8tR9CDha9s+BS8Wat53xZCj2GwoUtDetFQQcMQ9nJR4iGtVaWqiWvFWKmPAqBZPanw0InJ4Vfyj4qBSfFWqbRcpTL0iGlpMdhOVrdyAVdkj/igWkqWyguI0rx7w8GhxzRSSOiHbe0w+ORkbZT0ekMU46giolIJoxTY8VENAnpRixCEqF5fimuwTDIi8tw5cb2z5Hal7lb5FG2hXIntk50q90/zSFfTCWE+xkKE1ntV2tklRPfNR5PkCr8QtSQrTsRmoqgj/GnGubYWUNpVAWfpWl1CWm1LcICR3pgXC67bUscbqMS1lKCAsjVXkj9jC4eF0cW94atMTjldrt0yMw2HGZGUqSScoUOh/kUPbZjVzYL6NlZ98HsaUiy6qLlKhqXhSgOnTpRfBrhavRZX/eTjHr1FVdOZIJ+V4/ftXFWBJT8Y6Z0mtTHeocnarUselQLGO1Xh+Kg3m6qyz9a9Q3pWlQ7HNWXJB7VgZGRtUHdG6lvK6Rw80iZa21nGpB0K9Mf+YoxyC0EqIIIQkqVjfAHU/Slrhm6SIMhUZhUdAlFKFOvoCuVv8wztmukXVNpTwiwq9SZVtnlfwxGcAcUPVB2wR2NZVle5rQLK5oKdlTFe+RgpZfs+lKVKAwse6cjfNc59qVsULciQzhTbeW3SP6TnYHxXaeHIkhdquAcu0doJVqZdWhoLcx21eu3St1uu1jv1jmsszmlzFNcxyPLUCBpOc4OxIPipu1IlpFk/HprWvDrr5LkuttR2WyCg7Kwe4xtvUOFlk8VwsI1lbmgAb9auJlnn3e+XQx2wBEaLzqMA+7q2AA9Dn+KZfZyzb7HxtatSoy+c8Akr3KDjr6d66XUnyhu4ZCn+E0bgDhX7kIpWpJBCgcEEb1AwVeK7FxG1ZLlDW86hLM1tBXzkkALH2zvt5qg/SctyOHozBfaIzlvcj6irWLUmSDuxVLNpz4+shc6/JK8GoOReUNSh3p2VaSlRStCkkdQRg0q3dxBlKbaIKEbZHc96jWVwbEbHJwkJYjGMoGibbaVX26NRXJcdnX8vPyApXjV2P1oasrLOaHYK9pKuSkfvZ/o9roSfZdxDFbBZixl6M6dD+/32qvuHCl8jMvOTLI5ykNqJICXOx3yDmiuEPaVdbGhuPLzPhIGlKVqwtA8BXj0P2rov69sF+tUuO3MEWS6wtARIHLO6SPm+Xv5qPAwm91rKfVoZ22vY+ivlH2ZqmNybs9FKc+6hRWob5J2yf5oDispj8VwpENLPMUpC1NsAY1g7jHk13X8LlmQLDxCJ8dlxS5qUJbdSMkJTuRntvVHxNwvClfiQjRXEx49sZbRKdScNtpCU5wT0yTiicVnbgjcg4x/VVPz5E51yNGP5VtSMLZdSQoAjfA6ZoubxlPsDccRpMthaEBLSWjpSpI8k5zVr7SrXZYjyF8Nz0mSteHmG18xoD/IHcA+maU4vPaiqYdfU62oglJAxt4pbieDkodVqtPC0i93fExu8f3+82/lzlISNwlekayD3z/3VBWVlMjqyx9VUvqX73L/2Q==",
        "title": "Matías Ovalle",
        "body": "owo",
        "application_name": "WhatsApp",
        "package_name": "com.whatsapp",
        "notification_id": "1",
        "notification_tag": "ok41mYg7KFn/s5QmffvBcjBD5hvpEHWFW/YQ6JsRRxQ=\n",
        "conversation_iden": '{"package_name":"com.whatsapp","tag":"ok41mYg7KFn\\/s5QmffvBcjBD5hvpEHWFW\\/YQ6JsRRxQ=\\n","id":1}',
    },
}


{
    "type": "push",
    "targets": ["stream"],
    "push": {
        "type": "dismissal",
        "source_device_iden": "ujBuM9LadhssjB6hGMTY3U",
        "source_user_iden": "ujBuM9Ladhs",
        "package_name": "com.google.android.gm",
        "notification_id": "1249283767",
        "notification_tag": "gig:-224227955:^sq_ig_i_personal",
    },
}
